#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import argparse
from clippyl.coverage_graphics import coverage_graphics_cli

#            ####SUBPARSER BUILD CLEAVAGE DB
#            # create the subparser for the "build_cleav_db" command
#            parser` = subparsers.add_parser('build_cleav_db')
#            
#            #fastq files of adapter clipped-only reads; required
#            parser_hcg.add_argument('fq_files', nargs='+')
#            #TODO: output directory argument
#            parser_hcg.set_defaults(func=build_read_db_cli)

class Usage(Exception):
    def __init__(self, exitStat):
        self.exitStat = exitStat

def main(argv=None):
    if argv is None:
        argv = sys.argv
    try:
        try:
            
            #TODO: provide list of possible functions
            # create the top-level parser
            d = '''This is the CLI for generating coverage graphics using clippyl'''
            parser = argparse.ArgumentParser(description=d)
            
            #bam_fp_l, required
            parser.add_argument('bam_files', nargs='+')
            
            #query_bed_fp, required
            parser.add_argument('-q', '--query', nargs='?')
            
            #readid_db_fp_l, (optional kwarg)
            #note: there must be one cleav_file per bam_file
            parser.add_argument('--cleav_files', nargs='+')
            
            #ciselement_bed_fp_l
            parser.add_argument('-e', '--ciselements', nargs='+')
            
            #out_pdf_fp #TODO: use pwd as default
            parser.add_argument('-o', '--output', nargs='?')
            
            #only hits-clip is currently supported (optional kwarg)
            #TODO: incorporate code for par-clip and iclip
            parser.add_argument('--clipseq_method', choices=['hits-clip',],
                                default='hits-clip')
            
            parser.set_defaults(func=coverage_graphics_cli)
            
            # parse the args and call whatever function was selected
            args = parser.parse_args()
            print(args) #debugging
            args.func(args)
            
        except SystemExit as exitStat:
            raise Usage(exitStat)
    
    except Usage as err:
        return err.exitStat

main()

